version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio
    container_name: al-folio-website
    ports:
      - 8888:8888
      - 4000:4000
    volumes:
      - /DATA/jekyll:/srv/jekyll
      - /DATA/homepage:/srv/homepage