---
name: Sebastian
surname: Rowan
position: "Ph.D Candidate in Civil and Environmental Engineering"
pronouns: He/Him
address: "164 Boutwell St. Manchester, NH 03102"
www: sebastianrowan.github.io
email: "sebastian.rowan@unh.edu"
github: sebastianrowan
linkedin: "sebastian-rowan-72490170"
researchgate: false
orcid: false
aboutme: "Application - Senior Staff Environmental Data Analyst"
docname: "Cover Letter"
headcolor: "2698ba"
output:
  vitae::awesomecv:
    keep_tex: true
  engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
library(fontawesome)
```


\section{\protect{ }}

`r format(Sys.time(), '%B, %d %Y')`  
<br>  
<br>  
Geosyntec Consultants  
10 Corporate Dr. Suite 1600  
Bedford, NH 03110  
<br>  
<br>  
Dear Hiring Manager,  
<br>  
<br>  
I am writing to express my interest in the position of **Senior Staff Environmental Data Analyst**. I came across this job listing on LinkedIn and I believe I would be an excellent match for this role. 

Data management and data analysis have been fundamental skills throughout my professional and academic career. As a civil engineer with the NH Department of Transportation, I worked in the office of Asset Management, Performance, and Strategy where a core focus of our work was performing analyses to support operations throughout the DOT. My work in this role included developing data pipelines to produce standard reports to assess department-wide progress on performance metrics as well as to run one-off queries and analyses to answer specific questions from Department administrators. These tasks required a deep understanding of the various enterprise databases used by NHDOT and proficiency in SQL, Python, and occasionally VBA. 

I have continued to apply and develop these data analysis skills as a PhD student at the University of New Hampshire and research fellow with the US Army Corps of Engineers. My doctoral research focuses on developing new methodologies to comprehensively quantify the risks posed by floods by accounting for impacts that are typically excluded from monetary cost-benefit analyses. Doing this work requires me to identify data from a variety of sources and bring them together in a single analysis to answer my research questions. Through my graduate work, I have also become adaptable to new tools and programming languages. As an example, I am currently working on a nation-wide flood risk analysis using a tool called go-consequences, a hazard impact tool developed by USACE and written in the Go programming language. For this analysis, I had to implement several custom features in the program, requiring me to learn to code in Go and to understand the software and its internal data patterns. In implementing the features needed for my analysis, I was also able to significantly speed up the total run time of the program and fix a bug that caused the program to crash when working on certain large datasets.

Throughout my career I have developed the analytical and problem solving skills needed to succeed in this position and have a demonstrated track record of successfully applying these skills to new and unique challenges. 

Thank you for taking the time to review my application and consider me for this position. I am excited to learn more about this opportunity and I look forward to hearing from you soon!  
<br>  
<br>  
Sincerely,  
<br>  
<br>  
Sebastian Rowan
